/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
/**
 * Generated by vite-css-modules
 * https://npmjs.com/vite-css-modules
 */
const tooltipTrigger: string
const tooltip: string
const visible: string

export { tooltipTrigger, tooltip, visible }

export default {
  'tooltip-trigger': tooltipTrigger,
  tooltipTrigger,
  tooltip,
  visible,
}
