/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
/**
 * Generated by vite-css-modules
 * https://npmjs.com/vite-css-modules
 */
const tooltip: string
const visible: string

export { tooltip, visible }

export default {
  tooltip,
  visible,
}
